// apps/preview/nuxt/pages/pages/Cart/CartPage.vue
<template>
  <div>
    <NavbarTop />
    <div>Test product</div>
    <div class="my-20">
      <template v-for="index in 10" :key="index">
        <ReviewWithAvatar class="my-5" />
      </template>
    </div>
    <NavbarBottom />
  </div>
</template>

<script setup>
import { NavbarTop, NavbarBottom, WithAvatar as ReviewWithAvatar } from '@storefront-ui/vue-blocks';
</script>

// apps/preview/next/pages/pages/Cart/CartPage.tsx
import { ShowcasePageLayout } from '../../showcases';

// #region source
import { NavbarTop, NavbarBottom, WithAvatar as ReviewWithAvatar } from '@storefront-ui/react-blocks';

export default function CartPage() {
  return (
    <div>
      <NavbarTop />

      <ReviewWithAvatar />

      <NavbarBottom />
    </div>
  );
}

// #endregion source
CartPage.getLayout = ShowcasePageLayout;
